package model.response.ledger

import java.math.BigDecimal

/**
 * @property baseRate Exchange rate of the base pair. Each unit of the created curency will represent value of baseRate*1 basePair.
 * @property basePair Base pair for virtual currency. Transaction value will be calculated according to this base pair. e.g. 1 VC_VIRTUAL is equal to 1 BTC, if basePair is set to BTC.
 * @property customerId ID of customer associated with virtual currency.
 * @property description Used as a description within Tatum system.
 * @property name Virtual currency name. Must be prefixed with 'VC_'.
 * @property supply Supply of virtual currency.
 * @property accountId Virtual currency account.
 * @property erc20Address Address of ERC20 token.
 * @property issuerAccount Virtual currency account, on which initial supply was minted.
 * @property chain Blockchain, on which this virtual currency is paired on. Not present, when Tatum's private ledger is used as a base ledger.
 * @property initialAddress Ethereum address, where initial supply was minted.
 */
class VC(
    val baseRate: BigDecimal,
    val basePair: BasePairEnum,
    val customerId: String? = null,
    val description: String,
    val name: String,
    val supply: String,
    val accountId: String,
    val erc20Address: String? = null,
    val issuerAccount: String? = null,
    val chain: String? = null,
    val initialAddress: String? = null,
)

enum class BasePairEnum {
    AED,
    AFN,
    ALL,
    AMD,
    ANG,
    AOA,
    ARS,
    AUD,
    AWG,
    AZN,
    BAM,
    BAT,
    BBD,
    BCH,
    BDT,
    BGN,
    BHD,
    BIF,
    BMD,
    BND,
    BOB,
    BRL,
    BSD,
    BTC,
    BTN,
    BWP,
    BYN,
    BYR,
    BZD,
    CAD,
    CDF,
    CHF,
    CLF,
    CLP,
    CNY,
    COP,
    CRC,
    CUC,
    CUP,
    CVE,
    CZK,
    DJF,
    DKK,
    DOP,
    DZD,
    EGP,
    ERN,
    ETB,
    ETH,
    EUR,
    FJD,
    FKP,
    FREE,
    GBP,
    GEL,
    GGP,
    GHS,
    GIP,
    GMD,
    GNF,
    GTQ,
    GYD,
    HKD,
    HNL,
    HRK,
    HTG,
    HUF,
    IDR,
    ILS,
    IMP,
    INR,
    IQD,
    IRR,
    ISK,
    JEP,
    JMD,
    JOD,
    JPY,
    KES,
    KGS,
    KHR,
    KMF,
    KPW,
    KRW,
    KWD,
    KYD,
    KZT,
    LAK,
    LBP,
    LEO,
    LINK,
    LKR,
    LRD,
    LSL,
    LTC,
    LTL,
    LVL,
    LYD,
    MAD,
    MDL,
    MGA,
    MKD,
    MKR,
    MMK,
    MMY,
    MNT,
    MOP,
    MRO,
    MUR,
    MVR,
    MWK,
    MXN,
    MYR,
    MZN,
    NAD,
    NGN,
    NIO,
    NOK,
    NPR,
    NZD,
    OMR,
    PAB,
    PAX,
    PAXG,
    PEN,
    PGK,
    PHP,
    PKR,
    PLN,
    PLTC,
    PYG,
    QAR,
    RON,
    RSD,
    RUB,
    RWF,
    SAR,
    SBD,
    SCR,
    SDG,
    SEK,
    SGD,
    SHP,
    SLL,
    SOS,
    SRD,
    STD,
    SVC,
    SYP,
    SZL,
    THB,
    TJS,
    TMT,
    TND,
    TOP,
    TRY,
    TTD,
    TUSD,
    TWD,
    TZS,
    UAH,
    UGX,
    USD,
    USDC,
    USDT,
    UYU,
    UZS,
    VEF,
    VND,
    VUV,
    WST,
    XAF,
    XAG,
    XAU,
    XCD,
    XCON,
    XDR,
    XLM,
    XOF,
    XPF,
    XRP,
    YER,
    ZAR,
    ZMK,
    ZMW,
    ZWL,
}
